image: docker:git

services:
- docker:dind

stages:
- build_image

before_script:
- docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"

build_image.default:
  stage: build_image
  script:
  - docker buildx create --driver docker-container --use
  - docker buildx build
    --provenance=false
    --pull
    --build-arg BUILD_NAME="${CI_PROJECT_NAME}"
    --build-arg BUILD_DATE="$(date '+%FT%T.%s%z')"
    --build-arg BUILD_VCSREF="${CI_COMMIT_SHA:0:8}"
    --platform=linux/arm64,linux/amd64,linux/arm/v7
    --push
    -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
    .
  - docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}" "${CI_REGISTRY_IMAGE}:latest"
  - docker push "${CI_REGISTRY_IMAGE}:latest"
  only:
  - master
  except:
  - tags

build_image.feature:
  stage: build_image
  script:
  - docker buildx create --driver docker-container --use
  - docker buildx build
    --provenance=false
    --pull
    --build-arg BUILD_NAME="${CI_PROJECT_NAME}"
    --build-arg BUILD_DATE="$(date '+%FT%T.%s%z')"
    --build-arg BUILD_VCSREF="${CI_COMMIT_SHA:0:8}"
    --platform=linux/arm64,linux/amd64,linux/arm/v7
    --push
    -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME%%-*}"
    .
  only:
  - "/^[0-9]+-.*$/"
  except:
  - tags

build_image.nonstd:
  stage: build_image
  script:
  - docker buildx create --driver docker-container --use
  - docker buildx build
    --provenance=false
    --pull
    --build-arg BUILD_NAME="${CI_PROJECT_NAME}"
    --build-arg BUILD_DATE="$(date '+%FT%T.%s%z')"
    --build-arg BUILD_VCSREF="${CI_COMMIT_SHA:0:8}"
    --platform=linux/arm64,linux/amd64,linux/arm/v7
    --push
    -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME:0:128}"
    .
  only:
  - "/^[a-zA-Z]+.*$/"
  except:
  - master
  - dev
  - tags

build_image.tag:
  stage: build_image
  script:
  - docker buildx create --driver docker-container --use
  - docker buildx build
    --provenance=false
    --pull
    --build-arg BUILD_NAME="${CI_PROJECT_NAME}"
    --build-arg BUILD_DATE="$(date '+%FT%T.%s%z')"
    --build-arg BUILD_VCSREF="${CI_COMMIT_SHA:0:8}"
    --platform=linux/arm64,linux/amd64,linux/arm/v7
    --push
    -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
    .
  only:
  - tags

